---
- hosts: all
  tasks: 
    - name: Install packages
      packages: 
        name: "{{ item }}"
        state: present
      with_items:
        - httpd
        - php
        - telnet
        - lftp
